### ISSUE TITLE
Display error in binary editor

### ISSUE THREAD

**Issue by luigirosa** [zodiacon/RegExp#12]
Given this binary entry:

![image](https://user-images.githubusercontent.com/1075822/127811309-896ddf59-c964-4dd3-9eab-d8642e5c1a9d.png)

if I hit the **8** icon the visualization is this:
![image](https://user-images.githubusercontent.com/1075822/127811413-846208e7-05f7-42d6-8a52-63455518bbeb.png)

Tested with pre compiled 0.7  directly download from GitHub.

**Comment by zodiacon** [comment]
Fixed.
