### ISSUE TITLE
Request: connecting to other computers

### ISSUE THREAD

**Issue by humanpickle** [zodiacon/RegExp#14]
Can you integrate connecting to other computers as well

**Comment by zodiacon** [comment]
I was wondering how useful this really is?

**Comment by zodiacon** [comment]
I was wondering how useful this really is?

**Comment by adevries17** [comment]
In a domain environment, it becomes extremely useful for checking settings, or editing keys or properties without having to login to a user's session.

**Comment by endoleg** [comment]
Yes! Would be very useful!

**Comment by JavaLuigi** [comment]
OHHH YES! This is avery important feature. For me its killer feature :)

**Comment by LoZio** [comment]
Useful also in my opinion. Just connect to another machine instead of opening sessions and leaving credentials around

**Comment by zodiacon** [comment]
I'm convinced. Will add that as the next major feature.

**Comment by zodiacon** [comment]
Implemented in v0.8
