### ISSUE TITLE
Request: Context Menu

### ISSUE THREAD

**Issue by RomelSan** [zodiacon/RegExp#16]
Nice App.
Can you please add inside Locations a submenu "Context Menu".
And inside Context Menu add shortcuts for Context Menu:
```
HKEY_CLASSES_ROOT\*\shell
HKEY_CLASSES_ROOT\*\shellex
HKEY_CLASSES_ROOT\AllFileSystemObjects\ShellEx\ContextMenuHandlers  
HKEY_CLASSES_ROOT\Folder\shell
HKEY_CLASSES_ROOT\Folder\shellex\ContextMenuHandlers\  
HKEY_CLASSES_ROOT\Directory\shell
HKEY_CLASSES_ROOT\Directory\Background\shell  
HKEY_CLASSES_ROOT\Directory\Background\shellex\ContextMenuHandlers  
```
I mean to quickly edit the "Right click Menu"... Like:

![Right Click Context Menu](https://user-images.githubusercontent.com/11341002/128251569-d97bbb35-d376-4747-9daa-6c206f4d1d8a.JPG)

This is the result after editing manually my Registry... A tiring job.
The list was almost double. Size of Menu was From top screen to bottom.

**Comment by zodiacon** [comment]
Will be available in the next update where "locations" can be edited.
