### ISSUE TITLE
Fix instructions to build on VS2019

### ISSUE THREAD

**Issue by LoZio** [zodiacon/RegExp#17]
Other than setting toolset to v142 you also need to set the **C++ Language Standard** to **Preview feature from latest ...**
![image](https://user-images.githubusercontent.com/869890/128349219-84ce80a4-8e48-45da-a95a-6567c15cb130.png)

Else you'll get this:
`Element <LanguageStandard> has an invalid value of "stdcpp20".`

**Comment by zodiacon** [comment]
Correct, will fix.
