### ISSUE TITLE
Questions from first time user

### ISSUE THREAD

**Issue by vefatica** [zodiacon/RegExp#19]
What is "the real registry"?  Below, what are "A" and "WC"?  Thanks!
![image](https://user-images.githubusercontent.com/61856645/129070635-3d32accd-03ea-411c-aab9-fe9a85d80257.png)

**Comment by zodiacon** [comment]
In a nutshell: The real Registry is the Registry is it actually is. The hives we are familiar with are a limited projection, some more limited than others.
"WC" is used for the redirection for Windows Containers. "A" is used for redirection used by UWP processes.

**Comment by vefatica** [comment]
Thanks!
