### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by ImportTaste** [zodiacon/RegExp#2]
I don't have to edit the registry often, but when I do, it's an eye-searing experience. Please consider adding a dark mode.

Undocumented win32 API features are here if needed:
https://github.com/stefankueng/BowPad/issues/19
https://social.msdn.microsoft.com/Forums/en-US/e36eb4c0-4370-4933-943d-b6fe22677e6c/dark-mode-apis?forum=windowssdk
https://github.com/huanrenfeng/7zipDarkmode/commits/master (These commit diffs are particularly valuable examples)

**Comment by zodiacon** [comment]
I don't like these undocumented interfaces. For now, I have added a "lightweight" dark mode with an option to set dark background for the list view and tree view.
