### ISSUE TITLE
Question: RegExp portable

### ISSUE THREAD

**Issue by danno71** [zodiacon/RegExp#21]
Hello, is it possible to run RegExp on a portable device (e.g. USB stick)? The RegExp settings must then be stored accordingly on the USB stick.

Currently, the settings are stored in the registry so that you always have to remember to delete them after a use on a foreign PC.

**Comment by zodiacon** [comment]
Implemented in v0.8.2.

**Comment by danno71** [comment]
Thank you for your excellent work. :) 

I have adapted the source code a bit for my purposes to get around the limitation to USB sticks. 

My adaptation needs a file "PORTABLE" in the directory of the "RegExp.exe". If this file is present, RegExp is used in portable mode.

The modified sections can be found in the appendix. You may want to use them.

[RegExp_changed_files.zip](https://github.com/zodiacon/RegExp/files/6986905/RegExp_changed_files.zip)

**Comment by zodiacon** [comment]
Thanks, I'll consider your solution, or add an option for that.

**Comment by zodiacon** [comment]
Sounds reasonable :)
