### ISSUE TITLE
Handle Invalid on .reg Import

### ISSUE THREAD

**Issue by PrincessAkira** [zodiacon/RegExp#22]
I noticed the .reg Files you export have another Formatting that the .reg Files i want to Import (because theyre written by Hand).
Normal Regedit imports them Fine (if it would work for me atleast...) so im using this Program as working alternative.
The Particular Reg File/s is here.

https://paste.thighs.live/olycuhaqos.pl

**Comment by zodiacon** [comment]
Yes, it seems I need to escape quote characters... will fix.

**Comment by PrincessAkira** [comment]
Saw you fixxed it by a commit.
any chance for you to setup artifacts?
so people can pretest your stuff before you do a mainline release

**Comment by zodiacon** [comment]
I'll create a release with "Beta" in the name and once all fixes are complete, will delete that and recreate a release without the Beta.
