### ISSUE TITLE
Feature request: Open a path

### ISSUE THREAD

**Issue by saulrh** [zodiacon/RegExp#3]
I often land in `RegEdit.exe` when another tool launches it for me to inspect a particular key. When I tell Registry Explorer to replace `RegEdit.exe`, this functional no longer seems to function - when launched with a path to a key it simply opens to the root, exactly as if I'd launched it as an application. Similarly, if I have a path in my clipboard, there doesn't seem to be any textbox I can paste that path into to navigate to it.

**Comment by zodiacon** [comment]
Good ideas. I will implement.

**Comment by zodiacon** [comment]
done, I believe.
