### ISSUE TITLE
Please enable the "GitHub Discussions" feature

### ISSUE THREAD

**Issue by unforgettableid** [zodiacon/RegExp#35]
Dear @zodiacon:

Could you please enable the "GitHub Discussions" feature?  This might be useful both for users and for patch contributors.

It's quite easy to do.  If you wish to enable the feature, you simply:

* Go to https://github.com/zodiacon/RegExp/settings.
* Scroll down.
* Click the green "Set up discussions" button.
* Scroll down again.
* Click the green "Start discussion" button.

Any thoughts?

Thank you for reading this!

**Comment by zodiacon** [comment]
Done.
